### ISSUE TITLE
confusion

### ISSUE THREAD

**Issue by qiulesun** [Toneyaya/CGFormer#2]
@Toneyaya 
Nice work !

1. In this [line](https://github.com/Toneyaya/CGFormer/blob/main/model/layers.py#L338), self.cgattention2 is shared with the last two Group Transformer Layers.  Are you intentionally designing this?

2.  The implementation of Eq. 8 using this [line](https://github.com/Toneyaya/CGFormer/blob/main/model/layers.py#L343) is inconsistent with such illustration in paper that needs to compute the similarity between the referent query token and the global linguistic feature **e**.

3. The implementation of [LoadLayer ](https://github.com/Toneyaya/CGFormer/blob/main/model/layers.py#L237)does not consider pe_shape <= 30, meaning that the LoadLayer in the first Group Transformer Layer  is discarded, and in each  LoadLayer, only the referent query token is interacted with word features.  Are you intentionally designing this again?

4.  The paper claims that different query tokens can represent different objects/regions and the first one is to highlight referring object.   However,  in your implementation, only two query tokens are introduced, one is as referent query token and the other is to represent background. This may  not match your motivation, and  more query tokens (>2) may be a reasonable settting and meet your claim.

**Comment by Toneyaya** [comment]
Hi,
Thanks for your interest. Currently, we only release 2-tokens simplified version. For 2-tokens version, we find that there is no need to compute the similarity because it converges to certain referent token in early stage， so that we can specify it. Besides, we provide original and modified version of implementation of LoadLayer in the repo. It is observed that equally imposing the linguistic information on each token at the first level leads all the tokens to naturally focus on the referring region, impairing the model's ability to focus on different regions in the image.
We are preparing to release the multi-tokens version.

**Comment by qiulesun** [comment]
@Toneyaya 

Thanks for your reply.

For current 2-tokens version, its results are definitely different from that in paper. So could you provide the corresponding results on RIS datasets (or RefCOCO only) as a reference and comparison ?

I obtain the following results using current version with default setting except for batchsize that is set to 16 instead of 64.

RefCOCO (best_model.pth): 
oIoU:
val: 73.29, testA: 75.47, testB: 69.97

RefCOCO (last_model.pth): 
oIoU:
val: 73.43, testA: 75.78, testB: 70.05

**Comment by Toneyaya** [comment]
Thank you for your attention.
I would suggest trying out the default training parameters for optimal results. The results of the simplified version we have reproduced are close to the performance reported in the paper. We are working hard to release the full code as soon as possible.
